### PR TITLE
Force to remove all ANSI colors in the output of any git commands

### PR DESCRIPTION
**Pull request by Naereen**
See https://github.com/alberthier/git-webui/issues/32

### CODE REVIEW

**Comment by Naereen** [comment]
Thanks in advance @alberthier :+1: !

**Comment by alberthier** [comment]
Seems good to me
Thanks a lot for your contribution !

**Comment by Naereen** [comment]
You're welcome!

**Comment by Naereen** [comment]
@zorn-v I just don't understand what you want to say, sorry.

**Comment by zorn-v** [comment]
Try to open by NOT localhost (or just from another host) and you see 

and
```
code 403, message Forbidden
"POST /git HTTP/1.1" 403 -
```
in console

On localhost all works, coz you have write access and there https://github.com/alberthier/git-webui/pull/33/files#diff-7feb098bfe018fe419032f1ce8a49a9fR132 first check always true

```python
cmd = shlex.split("git -c color.ui=true " + codecs.decode(args, "utf-8"))
action = cmd[1]
```
Action ALWAYS  "-c" here, coz split("git -c color.ui=true")[1] == "-c"

**Comment by alberthier** [comment]
@zorn-v : You're right ! I'm going to fix that, thanks for the report

**Pull request merged**
