### PR TITLE
[WIP] Initial syntax highlighting support

### PR DESCRIPTION
**Pull request by desyncr**
This is a rough implementation. Addresses #9. Not absolutely happy with hightlightjs's defaults but I guess it could be tweaked.
Also not sure how to handle large diffsets. As highlighting will heavily impact on performance with large diffs.

All feedback welcome!

### CODE REVIEW

**Comment by alberthier** [comment]
Hi,

I tested your branch, but it isn't working for me. None of the source files appear highlighted.
Am I missing something ?

**Comment by desyncr** [comment]
Did you run it from src? Like <path to git-webui>/src/libexec/git-core/git-webui?

I'll take a look later. May be I forgot something.

**Comment by alberthier** [comment]
I ran it from `/dist/libexec/git-core/git-webui`
`/dist` is the files destination folder when you run `grunt`

It should contained the same files than `/src`. The difference is essentially *.less files compilation

**Comment by desyncr** [comment]
I ran `grunt` and then `git-webui` from `dist` and it worked. Granted syntax highlighting coloring is pretty poor IMHO.

**Comment by Jiab77** [comment]
You should move your javascript files from the body start to the body end for two reasons.

1. Browser standards
2. Loading speed

From:
```html
     <body>
          <script src="/js/jquery.min.js"></script>
          <script src="/js/bootstrap.min.js"></script>
          <script src="/js/git-webui.js"></script>
          <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.7/highlight.min.js"></script>
  
          <!-- Error modal dialog -->
          <div class="modal fade" id="error-modal" tabindex="-1" role="dialog">
```

To:
```html
     <body>
          <!-- Error modal dialog -->
          <div class="modal fade" id="error-modal" tabindex="-1" role="dialog">
          ....
          <script src="/js/jquery.min.js"></script>
          <script src="/js/bootstrap.min.js"></script>
          <script src="/js/git-webui.js"></script>
          <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.7/highlight.min.js"></script>
     </body>
```
In particular when you're loading external ressources, like you're doing with CDNJS.

If you're a lot concerned by rendering performance, you may avoid at max all browser reflow that can be cause by javascript loading time, and plenty other things

**Pull request closed without merging**
